# Generated by Django 5.2.8 on 2025-12-17 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerlike',
            name='is_like',
            field=models.BooleanField(default=True),
        ),
    ]
