# Generated by Django 5.2.8 on 2025-12-19 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rank',
            field=models.PositiveIntegerField(default=0, verbose_name='Позиция в топе'),
        ),
    ]
